spring:
  application:
    name: web-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app-02
    username: postgres
    password: akucintakamu

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
            show-sql: true
          cloud:
            refresh:
              enabled: false

server:
  port: 8090 
# port localhost